# Dependabot configuration for pushduck
# Automates dependency updates across the monorepo

version: 2
updates:
  # Main package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/pushduck"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "abhay-ramesh"
    assignees:
      - "abhay-ramesh"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "pushduck"
    # Group related packages together
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      typescript:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "@types/*"
      testing:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "@testing-library/*"
      build-tools:
        patterns:
          - "tsdown"
          - "bundlesize"
          - "eslint*"

  # CLI package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:15"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "abhay-ramesh"
    assignees:
      - "abhay-ramesh"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "cli"

  # Workspace root dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "abhay-ramesh"
    assignees:
      - "abhay-ramesh"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "workspace"

  # Documentation dependencies
  - package-ecosystem: "npm"
    directory: "/apps/docs"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 2
    reviewers:
      - "abhay-ramesh"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "documentation"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 2
    reviewers:
      - "abhay-ramesh"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
