# Dependabot configuration for pushduck
# Automates dependency updates across the monorepo with a single weekly PR

version: 2
updates:
  # All npm dependencies across the entire monorepo
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 1
    reviewers:
      - "abhay-ramesh"
    assignees:
      - "abhay-ramesh"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 1
    reviewers:
      - "abhay-ramesh"
    assignees:
      - "abhay-ramesh"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
