# Funding configuration for pushduck
# Support the development of this open source project

# GitHub Sponsors
github: [abhay-ramesh]

# Polar
# polar: abhay-ramesh

# Open Collective
# open_collective: pushduck

# Ko-fi
# ko_fi: abhay

# Tidelift
# tidelift: npm/pushduck

# Community Bridge
# community_bridge: pushduck

# Liberapay
# liberapay: abhay

# IssueHunt
# issuehunt: abhay

# Buy Me a Coffee
# buy_me_a_coffee: abhay

# Patreon
# patreon: abhay

# Custom funding URLs
custom:
  - "https://github.com/sponsors/abhay"
  # - "https://www.buymeacoffee.com/abhay"
  # - "https://ko-fi.com/abhay"
